name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          chmod +x build.sh
          ./build.sh
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bin/statusbar
            bin/statusbar-bin